name: dynamic_function
description: dynamic_function package was created mainly for supporting variable length parameter function for dart3.
version: 2025.427.1341
homepage: 
repository: https://github.com/dart-pkg/dynamic_function

environment:
  sdk: ^3.7.2
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.428.931
  test: ^1.25.15
