name: dynamic_function
description: "dynamic_function package project"
version: 1.0.4
homepage:
repository: https://github.com/dart-pkg/dynamic_function

environment:
  sdk: ^3.7.2

dependencies:

dev_dependencies:
  output: ^1.0.1
  lints: ^5.1.1
  test: ^1.25.15
